name: Gradr

on:
  push:
    branches:
    - main

jobs:    
  tor:
    name: Jah Nanla
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> "$GITHUB_ENV"
    - name: Use the value
      id: step_two
      run: echo "$action_state"